- include_tasks: 01_clean_node.yml
- include_tasks: 02_clone_node.yml
- name: Kubernetes NFS Block
  block:
    - name: 0.1 - Configure Nodes (Repos, Packages, etc)
      include_tasks: set_nfs.yml
      loop: "{{ storage_group_hosts }}"
      loop_control:
        loop_var: nfs_node
    