---
# 1.1 - Resolve latest K8s version
- name: 1.1 - Resolve latest K8s version
  ansible.builtin.uri:
    url: "https://dl.k8s.io/release/stable-kubernetes_version.txt" # Ensure kubernetes_version is defined
    return_content: yes
  delegate_to: localhost
  register: k8s_version_lookup

# 1.2 - Scrape Docker HTML Index
- name: 1.2 - Scrape Docker HTML Index
  ansible.builtin.uri:
    url: "https://download.docker.com/win/static/stable/x86_64/"
    return_content: yes
  delegate_to: localhost
  register: docker_index_page

- name: 1.3 - Extract Versions
  ansible.builtin.set_fact:
    k8s_actual_version: "{{ k8s_version_lookup.content | trim }}"
    docker_actual_version: "{{ docker_index_page.content | regex_findall('docker-([0-9]+\\.[0-9]+\\.[0-9]+)\\.zip') | sort | last }}"

- name: 1.4 - Ensure Chocolatey is installed
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present
  become: yes
  become_method: runas
  become_user: Administrator
  vars:
    ansible_become_password: "{{ ad_safe_mode_password }}"

- name: 1.5 - Download and Extract Docker
  ansible.windows.win_shell: |
    $url = "https://download.docker.com/win/static/stable/x86_64/docker-{{ docker_actual_version }}.zip"
    $dest = "$env:TEMP\docker.zip"
    curl.exe -L $url -o $dest
    Expand-Archive -Path $dest -DestinationPath "C:\Program Files" -Force
    Remove-Item $dest
  args:
    creates: C:\Program Files\Docker\dockerd.exe
  become: yes
  become_method: runas
  become_user: Administrator
  vars:
    ansible_become_password: "{{ ad_safe_mode_password }}"

- name: 1.6 - Enable Containers Feature
  ansible.windows.win_feature:
    name: Containers
    state: present
  become: yes
  become_method: runas
  become_user: Administrator
  vars:
    ansible_become_password: "{{ ad_safe_mode_password }}"
  register: feature_install

- name: 1.6.1 - Reboot for Features
  ansible.windows.win_reboot:
    msg: "Rebooting for Containers feature"
  when: feature_install.reboot_required

- name: 1.7 - Download Kubernetes Binaries
  ansible.windows.win_shell: |
    foreach ($bin in @("kubelet", "kubeadm", "kubectl")) {
        curl.exe -L "https://dl.k8s.io/release/{{ k8s_actual_version }}/bin/windows/amd64/$bin.exe" -o "C:\Windows\System32\$bin.exe"
    }
  args:
    creates: C:\Windows\System32\kubeadm.exe
  become: yes
  become_method: runas
  become_user: Administrator
  vars:
    ansible_become_password: "{{ ad_safe_mode_password }}"

- name: 1.8 - Create K8s Dir
  ansible.windows.win_file:
    path: C:\etc\kubernetes
    state: directory

- name: 1.9 - Register Docker Service
  ansible.windows.win_shell: |
    if (-not (Get-Service -Name docker -ErrorAction SilentlyContinue)) {
        & "C:\Program Files\Docker\dockerd.exe" --register-service
        Start-Service docker
    }
  become: yes
  become_method: runas
  become_user: Administrator
  vars:
    ansible_become_password: "{{ ad_safe_mode_password }}"