# - name: 1.3.4 - Set Lead Master Maintenance IP Fact
#   set_fact:
    # Change 'lead_m_ip' to 'golden_ip' to match your next tasks
    # golden_ip: "{{ lead_master_m_ip.stdout | trim }}"
- name: process nodes
  delegate_to: "{{ hostvars[cloud_node]['provision_ip'] | default('127.0.0.1') }}"
  become: yes
  vars:
    ansible_user: "{{ hostvars[cloud_node]['ansible_user'] | default('core') }}"
    n_zone: "{{ c_zone.replace(c_zone.split('.')[-1], 'local') }}"
  block:
    - name: "DNS Prep - clean resolve"
      ansible.builtin.shell: |     
          sed -i '/nameserver 172.16/d' /etc/resolv.conf
          echo 'search {{ c_zone }} {{ p_zone }} {{ n_zone }}' |tee /etc/resolv.conf > /dev/null
          echo 'nameserver {{ hostvars[groups['helpers'][0]]['provider_ip'] }}' |tee -a /etc/resolv.conf > /dev/null
          echo 'nameserver {{ hostvars[groups['ipa'][0]]['ansible_host'] }}' | tee -a /etc/resolv.conf > /dev/null
          echo 'nameserver {{ hostvars[groups['ipa'][1]]['ansible_host'] }}' | tee -a /etc/resolv.conf > /dev/null
      when: 
        - cloud_node not in groups['helpers']
        - cloud_node != 'localhost'

    - name: setup kube config permissions and placeholder
      become: yes
      shell: |
        {{ item }}
      loop:
        - "mkdir -p /home/core/.kube"
        - "chmod 750 /home/core/.kube"
        - "echo 'kubeconfig will be populated after cluster bootstrap' > /home/core/.kube/config"
        - "chmod 600 /home/core/.kube/config"

    # ============================================================
    # PLAY 2 — Provision Golden Image (runs inside VM)
    # ============================================================
    # --------------------------------------------------------
    # Install podman
    # --------------------------------------------------------
    - name: Install podman
      become: true
      shell: |
        dnf install -y podman
    # --------------------------------------------------------
    # Install kubeadm, kubelet, kubectl
    # --------------------------------------------------------
    - name: Install kubeadm, kubelet, kubectl
      shell: |
        dnf install -y kubeadm kubelet   kubectl

    # --------------------------------------------------------
    # Install crictl
    # --------------------------------------------------------
    - name: Set crictl version
      set_fact:
        crictl_version: "{{ lookup('env','crictl_version') | default('1.30.0', true) }}"

    - name: Download crictl
      become: false
      get_url:
        url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-amd64.tar.gz"
        dest: "/tmp/crictl.tar.gz"

    - name: upload crictl to golden-base and extract
      shell: |
        tar xzf /tmp/crictl.tar.gz -C /usr/local/bin/
        chmod 755 /usr/local/bin/crictl
        ln -s /usr/local/bin/crictl /usr/bin/crictl
        rm -f /tmp/crictl.tar.gz
        
    # Install cri-o
    # --------------------------------------------------------
    - name: Install cri-o
      shell: |
        dnf install -y cri-o

    # --------------------------------------------------------
    # Validate binaries
    # --------------------------------------------------------
    - name: Validate kubeadm
      shell: |
        kubeadm version
      register: kubeadm_check
      changed_when: false
      failed_when: kubeadm_check.rc != 0

    - name: Validate kubectl
      shell: |
        kubectl version --client=true
      register: kubectl_check
      changed_when: false
      failed_when: kubectl_check.rc != 0

    - name: Validate crictl
      command: "crictl --version"
      register: crictl_check
      changed_when: false
      failed_when: crictl_check.rc != 0

    # - name: setup kube config directory
    #   become: false
    #   file:
    #     path: /home/core/.kube
    #     state: directory
    #     mode: '0750'
    #     owner: core
    #     group: core

    # - name: create kubeconfig placeholder
    #   become: false
    #   copy:
    #     dest: /home/core/.kube/config
    #     content: "kubeconfig will be populated after cluster bootstrap\n"
    #     mode: '0600'
    #     owner: core
    #     group: core

    - name: set etcd_ver
      set_fact:
        etcd_ver: "{{ lookup('env','etcd_ver') | default('v3.5.12', true) }}"

    - name: Download ectd
      become: false
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v3.5.12/etcd-{{ etcd_ver }}-linux-amd64.tar.gz"
        dest: "/tmp/etcd-{{ etcd_ver }}-linux-amd64.tar.gz"

    - name: upload ectd to golden-base and extract
      shell: |
        tar xzf /tmp/etcd-{{ etcd_ver }}-linux-amd64.tar.gz -C /tmp --strip-components=1 etcd-{{ etcd_ver}}-linux-amd64/etcdctl
        mv /tmp/etcdctl /usr/local/bin/etcdctl
        chmod +x /usr/local/bin/etcdctl
        ln -s /usr/local/bin/etcdctl /usr/bin/etcdctl
        rm -f /tmp/etcd-{{ etcd_ver }}-linux-amd64.tar.gz

    - name: Clear dnf cache
      shell: |
        dnf clean all
      
    - name: Force disk sync inside VMs
      become: yes
      command: sync
      loop: "{{ groups['cluster_nodes'] | default([]) }}"

    # # --------------------------------------------------------
    # # Power off the golden image
    # # --------------------------------------------------------
    # - name: Power off golden image
    #   ignore_errors: true
    #   failed_when: false
    #   changed_when: false
    #   shell: |
    #     shutdown -h now
    #   when: 
    #     - cloud_node not in groups['helpers']
    #     - cloud_node != 'localhost'


    # # --------------------------------------------------------
    # # Power off the golden image (via KVM host, not SSH)
    # # --------------------------------------------------------
    # - name: Power off golden image
    #   shell: sudo virsh shutdown golden-base
    #   delegate_to: "{{ VM_HOST_IP }}"
    #   failed_when: false
    #   changed_when: false
    #   ignore_errors: true
    #   when: 
    #     - cloud_node not in groups['helpers']
    #     - cloud_node != 'localhost'

    # - name: Wait for golden image to be powered off
    #   shell: sudo virsh domstate golden-base
    #   register: golden_power
    #   until: golden_power.stdout == "shut off"
    #   retries: 30
    #   delay: 2
    #   delegate_to: "{{ VM_HOST_IP }}"
    #   when: 
    #     - cloud_node not in groups['helpers']
    #     - cloud_node != 'localhost'

    # - name: Sysprep the Master (On Hypervisor)
    #   delegate_to: "{{ VM_HOST_IP }}"
    #   become: true
    #   shell: |
    #     # We run this on the KVM host while the VM is OFF
    #     virt-sysprep -d {{ cloud_node }} \
    #       --operations machine-id,net-hostname,net-hwaddr,ssh-hostkeys,customize \
    #       --hostname {{ {{ hostvars[cloud_node]['hostname'] }}
    #   when: 
    #     - cloud_node not in groups['helpers']
    #     - cloud_node != 'localhost'