# - name: 1.3.4 - Set Lead Master Maintenance IP Fact
- name: Run on cloud nodes (excluding primary KVM host)
  when: 
    - cloud_node != (groups['kvm'][0] | default('none'))
    - cloud_node in groups['cluster_nodes']
  block:
    - name: processing task
      ansible.builtin.debug:
        msg: "Processing node: {{ cloud_node }}"    # ============================================================
    # PLAY 2 — Provision Golden Image (runs inside VM)
    # ============================================================
    # --------------------------------------------------------
    # Install podman
    # --------------------------------------------------------
    - name: Install podman
      become: true
      shell: |
        dnf install -y podman
    # --------------------------------------------------------
    # Install kubeadm, kubelet, kubectl
    # --------------------------------------------------------
    - name: Install kubeadm, kubelet, kubectl
      shell: |
        dnf install -y kubeadm kubelet kubectl bind-utils
  
    # roles/rocky_k8s_nodes/tasks/install_package.yml

    - name: Install system package baseline via shell
      become: yes
      ansible.builtin.shell: |
        sudo dnf install -y nfs-utils tar bzip2 jq socat conntrack
      changed_when: true

    # --------------------------------------------------------
    # Install crictl
    # --------------------------------------------------------
    - name: Set crictl version
      set_fact:
        crictl_version: "{{ lookup('env','crictl_version') | default('1.30.0', true) }}"

    - name: Download crictl
      become: false
      get_url:
        url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-amd64.tar.gz"
        dest: "/tmp/crictl.tar.gz"

    - name: upload crictl to golden-base and extract
      shell: |
        tar xzf /tmp/crictl.tar.gz -C /usr/local/bin/
        chmod 755 /usr/local/bin/crictl
        ln -s /usr/local/bin/crictl /usr/bin/crictl
        rm -f /tmp/crictl.tar.gz

    # Install cri-o
    # --------------------------------------------------------
    - name: Install cri-o
      shell: |
        dnf install -y cri-o

    # --------------------------------------------------------
    # Validate binaries
    # --------------------------------------------------------
    - name: Validate kubeadm
      shell: |
        kubeadm version
      register: kubeadm_check
      changed_when: false
      failed_when: kubeadm_check.rc != 0

    - name: Validate kubectl
      shell: |
        kubectl version --client=true
      register: kubectl_check
      changed_when: false
      failed_when: kubectl_check.rc != 0

    - name: Validate crictl
      command: "crictl --version"
      register: crictl_check
      changed_when: false
      failed_when: crictl_check.rc != 0

    - name: set etcd_ver
      set_fact:
        etcd_ver: "{{ lookup('env','etcd_ver') | default('v3.5.12', true) }}"

    - name: Download ectd
      become: false
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v3.5.12/etcd-{{ etcd_ver }}-linux-amd64.tar.gz"
        dest: "/tmp/etcd-{{ etcd_ver }}-linux-amd64.tar.gz"

    - name: upload ectd to golden-base and extract
      shell: |
        tar xzf /tmp/etcd-{{ etcd_ver }}-linux-amd64.tar.gz -C /tmp --strip-components=1 etcd-{{ etcd_ver}}-linux-amd64/etcdctl
        mv /tmp/etcdctl /usr/local/bin/etcdctl
        chmod +x /usr/local/bin/etcdctl
        ln -s /usr/local/bin/etcdctl /usr/bin/etcdctl
        rm -f /tmp/etcd-{{ etcd_ver }}-linux-amd64.tar.gz

    - name: Clear dnf cache
      shell: |
        dnf clean all

    - name: Force disk sync inside VMs
      become: yes
      command: sync
      loop: "{{ groups['cluster_nodes'] | default([]) }}"
    