---
- name: 0.1 - Run Pre-checks and Build Decision
  import_tasks: 00_pre_check.yml

- name: 0.2 - Debug Build Status
  debug:
    msg: "Rebuild requested: {{ rebuild_nodes | default(false) }} | Skipping Build: {{ skip_build }}"

- name: id_rsa.pub from helper nodes
  delegate_to: "{{ groups['helpers'][0] }}"
  vars:
    ansible_user: "{{ hostvars[groups['helpers'][0]]['ansible_user'] }}"
  become: false
  slurp:
    src: ~/.ssh/id_rsa.pub
  register: id_rsa_pub_content

- name: Set id_rsa.pub content as fact
  set_fact:
    id_rsa_pub_content_decoded: "{{ id_rsa_pub_content.content | b64decode }}"

- name: set chrony
  import_tasks: set_chrony.yml

- name: Kubernetes Node Provisioning Block
  block:
    # - import_tasks: 00_dns_register.yml
    - name: 0.3 - Clone First Node and Set Hostnames
      import_tasks: 01_clone_first_node.yml
    
    - name: 0.4 - Configure Nodes (Repos, Packages, etc)
      include_tasks: 02_configure_nodes.yml
      loop: "{{ groups['cluster_nodes'] }}"
      loop_control:
        loop_var: cloud_node

  when: not skip_build | bool
