- name: 1.11 - Copy and run installation script
  block:
    - name: Copy script to remote
      ansible.windows.win_copy:
        src: ../files/install_cri.ps1
        dest: C:\Windows\Temp\install_cri.ps1

    - name: Execute installation script
      ansible.windows.win_shell: C:\Windows\Temp\install_cri.ps1
      become: yes
      become_method: runas
      become_user: Administrator
      vars:
        ansible_become_password: "{{ ad_safe_mode_password }}"