---
# roles/rocky_k8s/tasks/main.yml
- import_tasks: pre-check.yml
  # when: rebuild_win is defined

- import_tasks: deploy.yml
  when: not skip_win_build | bool

- import_tasks: patching.yml
  when: not skip_win_build | bool

- import_tasks: reconnect.yml
  when: not skip_win_build | bool

- import_tasks: configure_forest.yml
  when: not skip_win_build | bool
# - debug:
#     msg: "Administrator {{ ad_safe_mode_password }} or {{ ad_admin_password }}"

- import_tasks: docker_install.yml
- import_tasks: docker_join.yml

