- name: 0.1 - Check if Windows Nodes already exist
  delegate_to: "{{ kvm_ip }}"
  become: yes
  vars:
    ansible_user: "{{ hostvars[kvm.split('.')[0]]['ansible_user'] }}"
  shell: |
    if virsh list --all | grep -q "hostvars[inventory_hostname.split('.')[0]] }}"; then
      echo "exists"
    else
      echo "missing"
    fi
  register: win_vm_check
  
- debug:
    var: skip_win_build

- name: 0.2 - Determine if Windows Build is Required
  set_fact:
    # Check stdout of the specific host's check
    skip_win_build: "{{ not (rebuild_win | default(false) | bool) and ('missing' not in win_vm_check.stdout) }}"

- debug:
    var: skip_win_build

- name: host name chech
  delegate_to: "{{ kvm_ip }}"
  vars:
    ansible_user: "{{ hostvars[kvm.split('.')[0]]['ansible_user'] }}"
  debug:
    msg: "Host {{ inventory_hostname.split('.')[0] }} is being{{ rebuild_win | default(false) }} " 

- name: 0.3 - Cleanup for Windows Rebuild (Only if forced)
  delegate_to: "{{ kvm_ip }}"
  become: yes
  when: rebuild_win | default(false) | bool
  vars:
    ansible_user: "{{ hostvars[kvm.split('.')[0]]['ansible_user'] }}"
  shell: |
    # Properly resolve the VM name into a shell variable
    VM="{{ inventory_hostname.split('.')[0] }}"
    
    # Run commands and capture output
    virsh destroy "$VM" || true
    virsh undefine "$VM" --remove-all-storage --nvram || true
    rm -f /var/lib/libvirt/images/"$VM".qcow2
  register: cleanup_output

- name: 0.4 - Cleanup for Windows Rebuild pause
  pause:
    seconds: 5
  when: rebuild_win | default(false) | bool
