- name: Initialize guest configuration map
  set_fact:
    guest_configs: {}
    golden_image_raw: none
    skip_config: true

- name: determine which image to clone.
  import_tasks: 01_determine_os_identity.yml

- name: Annouce the deployment type
  debug:
    msg: "{{ guest_member }} is being cloned from {{ guest_configs[guest_member] }}"

- name: Update Build Profile
  set_fact: 
    build_profile: "{{ guest_configs[guest_member].profile }}"
    
- name: Cloning guest hosts
  import_tasks: 02_clone_to_guest.yml

- name: check if the image is already "Sealed"
  vars:
    nat_seg: "{{ net_maintenance }}"
    pro_seg: "{{ net_provider }}"
    cld_seg: "{{ net_provision }}"
  include_tasks: pre_clone.yml

- name: Run Guest Configuration
  include_tasks: 03_Config_guest.yml
  # Only run if the node is NOT reachable OR we explicitly requested a reclone
  when: not skip_config | bool

# - name: Update Member network connectivity
#   import_tasks: 03_Config_guest.yml
- name: post initialise fips
  vars:
    pro_seg: "{{ net_provider }}"
  include_tasks: post_clone.yml
  when: guest_member in groups['helpers']