TASK [rocky_dns_cloud : Create the cloud sub-zone] *****************************
[ERROR]: Task failed: Module failed: non-zero return code
Origin: /opt/ansible_work/cloud/ansible/roles/rocky_dns_cloud/tasks/add_cloud_zones.yml:12:7

10
11     # STEP 1: Create the Cloud Zone
12     - name: Create the cloud sub-zone
         ^ column 7

fatal: [helper -> ipa01(192.168.100.10)]: FAILED! => {"changed": false, "cmd": "ipa dnszone-add  }} --author-email=admin@home.morinsoft.ca --force\n", "delta": "0:00:00.302319", "end": "2026-04-22 04:53:30.613210", "failed_when_result": "Error while evaluating conditional: 'dns_create' is undefined", "msg": "non-zero return code", "rc": 2, "start": "2026-04-22 04:53:30.310891", "stderr": "Usage: ipa [global-options] dnszone-add NAME [options]\n\nipa: error: no such option: --author-email", "stderr_lines": ["Usage: ipa [global-options] dnszone-add NAME [options]", "", "ipa: error: no such option: --author-email"], "stdout": "", "stdout_lines": []}

TASK [rocky_dns_cloud : Destroy Kerberos ticket] *******************************
ok: [helper -> ipa01(192.168.100.10)]