- name: reboot
  ansible.windows.win_reboot:
    pre_reboot_command: |
      powershell.exe -Command "if (Test-Path 'C:\tools\persist.exe') { & 'C:\tools\persist.exe' --commit }; Get-Volume C | Flush-Volume"
    reboot_timeout: 600