---
- name: 1.1 - Deploy Stack via Native Kubectl Shell
  ansible.builtin.shell: |
    kubectl --kubeconfig=/home/core/.kube/config apply -f dex-and-portainer.yaml
  args:
    executable: /bin/bash
  register: kubectl_output

- name: 1.2 - Output Deployment Results
  ansible.builtin.debug:
    var: kubectl_output.stdout_lines
