---
- name: 1.1 - Deploy Stack via Native Kubectl Shell
  ansible.builtin.shell: |
    apply -f dex-and-portainer.yaml
  register: kubectl_output

- name: 1.2 - Output Deployment Results
  ansible.builtin.debug:
    var: kubectl_output.stdout_lines
