# 1. Fetch the config to the Ansible controller (helper)
- name: 4.1 - Fetch admin.conf to controller temp
  become: yes
  fetch:
    src: /etc/kubernetes/admin.conf
    # We save it to a temp path on the helper where we have guaranteed access
    dest: "/tmp/admin.conf"
    flat: yes
  when: inventory_hostname == groups['control_nodes'][0]

# - name: insure folder in home all belongs to core
#   delegate_to: localhost
#   run_once: true
#   become: yes
#   shell: |
#     # Create the directories if they don't exist
#     mkdir -p /home/core/.kube
#     # Recursively set ownership to core:core
#     chown -R core:core /home/core
#     # Set proper directory permissions
#     chmod 700 /home/core /home/core/.kube

# - name: insure folder in home all belongs to core
#   become: yes
#   shell: |
#     # Create the directories if they don't exist
#     mkdir -p /home/core/.kube
#     # Recursively set ownership to core:core
#     chown -R core:core /home/core
#     # Set proper directory permissions
#     chmod 700 /home/core /home/core/.kube

- name: 4.1b - Ensure KUBECONFIG is present on localhost
  become: yes
  delegate_to: localhost
  run_once: true
  ansible.builtin.shell: |
    mkdir -p /home/core/.kube && \
    cp /tmp/admin.conf /home/core/.kube/config && \
    chown -R core:core /home/core/.kube && \
    chmod 700 /home/core /home/core/.kube && \
    chmod 600 /home/core/.kube/config

- name: 4.2 - Distribute kubeconfig to remote nodes
  become: yes
  when: inventory_hostname != 'helper'  # Skip the helper since we did it in 4.1b
  block:
    - name: Ensure remote .kube directory exists
      ansible.builtin.file:
        path: "/home/core/.kube"
        state: directory
        owner: core
        group: core
        mode: '0700'

    - name: Copy config to remote nodes
      ansible.builtin.copy:
        src: "/tmp/admin.conf"
        dest: "/home/core/.kube/config"
        owner: core
        group: core
        mode: '0600'

- name: 4.4 - Apply Flannel Pod Network (Fixed Interface)
  shell: |
    # 1. Download the latest manifest
    curl -sLO https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    
    # 2. Inject the --iface flag into the container arguments
    # This forces Flannel to use enp2s0 for the VXLAN tunnel
    sed -i '/- --kube-subnet-mgr/a \        - --iface=enp2s0' kube-flannel.yml
    
    # 3. Apply the modified manifest
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f kube-flannel.yml
  delegate_to: "{{ groups['control_nodes'][0] }}"
  run_once: true
  become: true

# . Automated Wait for 'Ready' Status
- name: 4.6 - Wait for all 5 nodes to transition to Ready
  shell: "kubectl get nodes | grep ' Ready ' | wc -l"
  delegate_to: localhost
  register: ready_count
  # We expect 5 (msrlv9mast01-03 + msrlv9wrk01-02)
  until: ready_count.stdout | trim | int == 5
  retries: 30
  delay: 10
  run_once: true
  environment:
    KUBECONFIG: "/home/core/.kube/config"