---
# 1. Run verification on ALL nodes first
- import_tasks: 01_k8s_verify.yml

# 2. Run Initialize ONLY on the first master
- import_tasks: 02_k8s_initialize.yml

# 3. Run Join on everything else
- import_tasks: 03_k8s_join.yml

# 4. run post init
- import_tasks: 04b_fix_firewall.yml
- import_tasks: 04_post_init.yml

# - name: Setup Dashboard Infrastructure
#   ansible.builtin.import_tasks: dashboard.yml
#   when: inventory_hostname in groups['masters'][0]

# - name: Verify Dashboard and Get Token
#   ansible.builtin.import_tasks: verify_dashboard.yml
#   when: inventory_hostname in groups['masters'][0]

# 5. test it
- import_tasks: 05_smoke_test.yml

# 7. Setup MetalLB and Test Ingress
- import_tasks: 07_setup_metallb.yml
  when: inventory_hostname == groups['control_nodes'][0]

# 6. Pre-check MetalLB IP range
- import_tasks: 06_setup_bridge.yml
