- name: Deploy
  gather_facts: false
  hosts: helper  # Should be the IPA master
  become: true
  roles:
    - role: rocky_dns_cloud

- name: DNS population
  gather_facts: false
  hosts: all  # Should be the IPA master
  become: true
  roles:
    - role: rocky_dns_entries

# Build Golden Base (Conditional)
# 1. Prepare Environment
- name: Build Kubernet Images
  vars:
    BUILD_PROFILE: "k8s"
  hosts: kvm
  gather_facts: false
  roles:
    - role: rocky_k8s_golden

# Deploy Infrastructure (LBs and Base Config)
- name: Deploy Cluster Infrastructure
  hosts: kvm
  gather_facts: false
  vars:
    BUILD_PROFILE: "k8s"
  roles:
    - role: rocky_k8s_lbs
    # You can uncomment and add rocky_k8s_base here if needed

# 4. Deploy Infrastructure (LBs and Base Config)
- name: Deploy Cluster nodes
  hosts: kvm
  gather_facts: false
  vars:
    BUILD_PROFILE: "k8s"
  roles:
    - role: rocky_k8s_nodes

- name: Set Chrony and Timezone 
  gather_facts: false
  hosts: all:!kvm
  become: false
  roles:
    - role: rocky_k8s_chrony

# # 5. Initialize Kubernetes Cluster
- name: Initialize Kubernetes Cluster
  hosts: cluster_nodes:!helpers
  remote_user: core
  become: true
  gather_facts: true
  vars:
    # Pulling from environment script via lookup
    cluster_token: "{{ lookup('env', 'K8S_CLUSTER_TOKEN') }}"
    # Pulling from inventory.yml vars
    api_vip: "{{ k8s_api_vip }}"
  roles:
    - role: rocky_k8s_init

- name: Environment Setup & Identity Control Deployment
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Explicitly overrides the fallback profile value inside defaults
    BUILD_PROFILE: "k8s"
  roles:
    - role: rocky_k8s_storage

# - name: Pillar 1 - Base Kubernetes Hardening
#   hosts: cluster_nodes
#   become: true
#   gather_facts: true

#   roles:
#     - rocky_k8s_pillar_1
