# # STAGE 1b: Windows Infrastructure - AD Creation
# - name: "Stage 1b: Build Windows AD Forest"
#   gather_facts: false
#   hosts: all:!kvm
#   become: false
#   roles:
#     - role: win_k8s_ad_promotion
  
- name: Test Docker Install
  hosts: all:!kvm
  gather_facts: false
  tasks:
    - name: Run only the docker_install task file
      ansible.builtin.import_tasks: ../roles/win_k8s_ad_promotion/tasks/docker_install.yml