---
- name: Determine NTP source list
  ansible.builtin.set_fact:
    raw_ntp: "{{ nrc_ntp_list | default(lookup('env', 'ntp_servers')) | default('time.nrc.ca,time.chu.nrc.ca', true) }}"

- name: Final List Conversion
  ansible.builtin.set_fact:
    nrc_ntp_list: "{{ raw_ntp if raw_ntp | type_debug == 'list' else raw_ntp.split(',') }}"

- name: Find primary IPA host
  ansible.builtin.set_fact:
    ipa_primary_host: >-
      {%- for host in groups['ipa'] -%}
        {%- if hostvars[host]['ipa_cluster_role'] | default('') == 'primary' -%}
          {{ hostvars[host]['ansible_host'] }}
        {%- endif -%}
      {%- endfor -%}

# Use a block to apply delegation specifically for the helper node
- name: Chrony Configuration Block
  block:
    - name: Install chrony
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Configure chrony.conf
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        mode: '0644'
      notify: Restart Chrony

    - name: Enable and start chronyd
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
  # If the current host is in the helpers group, do it on localhost
  delegate_to: "{{ 'localhost' if inventory_hostname in groups['helpers'] else inventory_hostname }}"
  become: yes