---
# Kubeconfig configuration
kubeconfig_path: "/home/core/.kube/config"

# Network & Domain Configuration
ad_domain_controller_ip: "192.168.100.30"
ad_domain_ldap_port: 389
ad_base_dn: "dc=yourdomain,dc=local"
ad_bind_dn: "cn=AnsibleService,ou=ServiceAccounts,dc=yourdomain,dc=local"
ad_bind_password: "YourSecurePassword"

# Target routing IPs (Update to match your entry point/ingress/helper routing)
dex_issuer_url: "http://10.244.4"
portainer_redirect_url: "http://10.244.4"
portainer_oauth_secret: "portainer-super-secret-key"
