# 00_pre_registration.yml
---
- name: Register DNS Records via Localhost
  run_once: true
  delegate_to: localhost
  become: no
  block:
    - name: Authenticate with FreeIPA
      shell: "echo '{{ ipa_admin_password }}' | kinit admin"
      no_log: true

    - name: Ensure DNS Forward and Reverse Zones exist
      command: "ipa dnszone-add {{ item }} --name-server={{ ipa_master_fqdn }}."
      loop: 
        - "{{ c_zone }}"
        - "{{ rev_cloud }}"
      register: zone_create
      failed_when: 
        - zone_create.rc != 0 
        - "'already exists' not in zone_create.stderr"
      changed_when: "'Added zone' in zone_create.stdout"

    - name: Add Forward & Reverse for individual LB nodes
      shell: |
        # Use short name for the record, ansible_host for the IP
        SHORT_NAME={{ item.split('.')[0] }}
        IP={{ hostvars[item].ansible_host }}
        
        ipa dnsrecord-add {{ c_zone }} $SHORT_NAME --a-rec=$IP
        ipa dnsrecord-add {{ rev_cloud }} ${IP##*.} --ptr-rec=$SHORT_NAME.{{ c_zone }}.
      loop: "{{ groups['hahost'] }}"
      register: dns_nodes
      failed_when: 
        - dns_nodes.rc != 0 
        - "'already exists' not in dns_nodes.stderr"
        - "'no modifications' not in dns_nodes.stderr"


- name: Register K8s Infrastructure (VIP) in FreeIPA
  delegate_to: localhost
  run_once: true
  block:
    - name: Authenticate with FreeIPA
      shell: "echo '{{ ipa_admin_password }}' | kinit admin"
      no_log: true
    
    - name: Add Forward A Record for VIP
      command: >
        ipa dnsrecord-add {{ c_zone }} k8s-api 
        --a-rec={{ k8s_api_vip }}
      register: dns_vip
      failed_when: 
        - dns_vip.rc != 0 
        - "'already exists' not in dns_vip.stderr"
        - "'no modifications' not in dns_vip.stderr"

    - name: Add Reverse PTR Record for VIP
      command: >
        ipa dnsrecord-add {{ rev_cloud }} {{ k8s_api_vip.split('.')[-1] }} 
        --ptr-rec=k8s-api.{{ c_zone }}.
      register: ptr_vip
      failed_when: 
        - ptr_vip.rc != 0 
        - "'already exists' not in ptr_vip.stderr"
        - "'no modifications' not in ptr_vip.stderr"

