# 02_configure_lbs.yml 
---
- name: "DNS Prep - clean resolve"
  delegate_to: localhost
  become: false
  ansible.builtin.shell: |     
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@{{ hostvars[item]['provider_ip'] }} "
      sudo sed -i '/nameserver 172.16/d' /etc/resolv.conf && \
      echo 'search {{ c_zone }} {{ p_zone }} {{ c_zone.replace(c_zone.split('.')[-1], 'local') }}' | sudo tee /etc/resolv.conf > /dev/null && \
      echo 'nameserver {{ hostvars[groups['helpers'][0]]['provider_ip'] }}' | sudo tee -a /etc/resolv.conf > /dev/null && \
      echo 'nameserver {{ hostvars[groups['ipa'][0]]['ansible_host'] }}' | sudo tee -a /etc/resolv.conf > /dev/null && \
      echo 'nameserver {{ hostvars[groups['ipa'][1]]['ansible_host'] }}' | sudo tee -a /etc/resolv.conf > /dev/null"
  loop: "{{ groups['hahost'] }}"

- name: Install HA Software Stack
  delegate_to: localhost
  become: false
  shell: |
    ssh core@{{ hostvars[item]['provider_ip'] }} "sudo dnf install --nobest -y haproxy keepalived policycoreutils-python-utils"
  loop: "{{ groups['hahost'] }}"

- name: Process Load Balancer configurations
  include_tasks: haproxy_cfg.yml
  loop: "{{ groups['hahost'] }}"
  loop_control:
    loop_var: lb_node

- name: Set HAProxy and Keepalived to SELinux permissive mode
  become: yes
  shell: |
    # Check if they are already permissive to avoid errors
    if ! semodule -l | grep -q "permissive_haproxy_t"; then
      semanage permissive -a haproxy_t
    fi
    if ! semodule -l | grep -q "permissive_keepalived_t"; then
      semanage permissive -a keepalived_t
    fi

- name: Force disk sync inside VMs
  become: yes
  command: sync
  delegate_to: "{{ item }}"
  loop: "{{ groups['hahost'] }}"

- name: Create Isolated Dummy Network
  vars:
    # This forces the connection to use 'secops' from the KVM host's variables
    ansible_user: "{{ hostvars[kvm_host]['ansible_user'] }}"
  become: yes
  shell: |
    if ! virsh net-info black-hole >/dev/null 2>&1; then
      cat <<EOF > /tmp/black-hole.xml
      <network><name>black-hole</name></network>
    EOF
      virsh net-define /tmp/black-hole.xml
      virsh net-autostart black-hole
      virsh net-start black-hole
    fi
