- name: "Deployment for {{ lb_node }}"
  delegate_to: "{{ hostvars[lb_node]['ansible_host'] }}"
  vars:
    ansible_user: "{{ hostvars[lb_node]['ansible_user'] | default('core') }}"
  # Use the user from hostvars or fallback to 'core'
  block:
    - name: System level tweaks for HAProxy
      shell: |
        # 1. Enable non-local binding (allow binding to the VIP)
        sysctl -w net.ipv4.ip_nonlocal_bind=1
        echo "net.ipv4.ip_nonlocal_bind = 1" > /etc/sysctl.d/99-haproxy.conf
        
        # 2. Update SELinux to allow HAProxy on K8s API port
        if [ "$(getenforce)" != "Disabled" ]; then
          semanage port -a -t http_port_t -p tcp 6443 || semanage port -m -t http_port_t -p tcp 6443
        fi
      become: yes

    - name: Push HAProxy and Keepalived configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { src: 'haproxy.cfg.j2', dest: '/etc/haproxy/haproxy.cfg' }
        - { src: 'keepalived.conf.j2', dest: '/etc/keepalived/keepalived.conf' }

    - name: Validate HAProxy Configuration
      command: haproxy -c -f /etc/haproxy/haproxy.cfg
      register: haproxy_check
      changed_when: false

    - name: Restart Load Balancer Services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - keepalived
        - haproxy
      when: haproxy_check.rc == 0